name: cainjector
apiVersion: v1
version: "v0.7.2"
appVersion: "v0.7.2"
description: A Helm chart for deploying the cert-manager cainjector component
home: https://github.com/jetstack/cert-manager
sources:
  - https://github.com/jetstack/cert-manager
keywords:
  - cert-manager
  - kube-lego
  - letsencrypt
  - tls
maintainers:
  - name: munnerz
    email: james@jetstack.io
