name: webhook
apiVersion: v1
# The version and appVersion fields are set automatically by the release tool
version: v0.1.0
appVersion: v0.1.0
description: A Helm chart for deploying the cert-manager webhook component
home: https://github.com/jetstack/cert-manager
sources:
  - https://github.com/jetstack/cert-manager
keywords:
  - cert-manager
  - kube-lego
  - letsencrypt
  - tls
maintainers:
  - name: munnerz
    email: james@jetstack.io
