---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bind
data:
  named.conf: |
    options {
    	directory "/var/cache/bind";
    	dnssec-validation auto;
    	auth-nxdomain no;    # conform to RFC1035
    	listen-on port 8053 { any; };
    	max-cache-size 192m;
    };

    controls { };

    zone "example.com" {
      type master;
      file "/etc/bind/example.com";
      allow-update { any; };
    };

  example.com: |
    $TTL 30
    @	IN	SOA	localhost. root.localhost. (
    			      1		; Serial
    			 604800		; Refresh
    			  86400		; Retry
    			2419200		; Expire
    			 604800 )	; Negative Cache TTL
    @	IN	NS	localhost.
    *.ingress-nginx.http01	IN  A {SERVICE_IP_PREFIX}.15
    ingress-nginx.http01	IN	A {SERVICE_IP_PREFIX}.15
    *.gateway.http01 IN  A {SERVICE_IP_PREFIX}.14
    gateway.http01 IN  A {SERVICE_IP_PREFIX}.14
