apiVersion: v1
kind: Service
metadata:
  name: {{ template "webhook.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ include "webhook.name" . }}
    app.kubernetes.io/name: {{ include "webhook.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: "webhook"
    {{- include "labels" . | nindent 4 }}
{{- if .Values.webhook.serviceLabels }}
{{ toYaml .Values.webhook.serviceLabels | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.webhook.serviceType }}
  {{- if .Values.webhook.loadBalancerIP }}
  loadBalancerIP: {{ .Values.webhook.loadBalancerIP }}
  {{- end }}
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: {{ .Values.webhook.securePort }}
  selector:
    app.kubernetes.io/name: {{ include "webhook.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: "webhook"
