# Default values for cert-manager.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

image:
  repository: jetstackexperimental/cert-manager-controller
  tag: v0.1.1
  pullPolicy: Always

createCustomResource: true

rbac:
  enabled: true

resources: {}
